export type Stage = "proposal" | "approved" | "executing" | "verified" | "unknown";
export type Layer = "central" | "research" | "local" | "industry" | "association";

export type PublicInfo = {
  news: string[];
  announcements: string[];
  openData: string[];
};

export const sourceCatalog = {
  ey: {
    label: "行政院全球資訊網",
    url: "https://www.ey.gov.tw/",
    note: "政策新聞、院會與跨部會計畫線索。",
  },
  nstc: {
    label: "國科會全球資訊網",
    url: "https://www.nstc.gov.tw/",
    note: "科技計畫、研究補助、新聞資料與查詢入口。",
  },
  gstp: {
    label: "政府科技計畫資訊網",
    url: "https://gstp.stpi.narl.org.tw/",
    note: "跨部會科技計畫與年度科技預算查詢入口。",
  },
  grb: {
    label: "政府研究資訊系統 GRB",
    url: "https://www.grb.gov.tw/",
    note: "研究計畫名稱、主持人、關鍵字與成果摘要查詢。",
  },
  sports: {
    label: "運動部全民運動署",
    url: "https://www.sa.gov.tw/",
    note: "運動科技、場域、補助與政策公告入口。",
  },
  dgbas: {
    label: "行政院主計總處",
    url: "https://www.dgbas.gov.tw/",
    note: "中央政府預算、決算與補捐助資訊入口。",
  },
  pcc: {
    label: "公共工程委員會",
    url: "https://www.pcc.gov.tw/",
    note: "政府採購、決標與委辦案追蹤入口。",
  },
  data: {
    label: "政府資料開放平臺",
    url: "https://data.gov.tw/",
    note: "open data 資料集與 API 查詢入口。",
  },
} as const;

export type SourceKey = keyof typeof sourceCatalog;

export const stages: Record<Stage, string> = {
  proposal: "提案/爭取",
  approved: "已核定",
  executing: "執行中",
  verified: "已有成果",
  unknown: "待公開對帳",
};

export const layerNames: Record<Layer, string> = {
  central: "中央預算",
  research: "科研/學研",
  local: "地方場域",
  industry: "產業新創",
  association: "協會應用端",
};

export const metrics = [
  {
    label: "政策總額",
    value: "46 億元",
    note: "跨部會、跨年度政策總額，不能直接視為運動部單一預算。",
    detailTitle: "政策總額怎麼讀",
    detail:
      "46 億元比較像一個政策總盤，不是一張已經花出去的帳單。閱讀時先問：這筆錢原本由誰核定？分到哪些部會？後來是否變成年度預算、地方補助或採購案？",
    flow: ["政策核定", "年度預算", "分案/採購", "驗收/成果"],
    flowRoles: ["行政院/科技會報", "主計總處與各部會", "地方政府或委辦廠商", "場域、使用者與成果報告"],
    flowIcons: ["badge-check", "calendar-days", "file-search", "circle-check"],
    checks: [
      "先確認行政院或科技會報核定的是政策總額、計畫期程與主責部會。註：政策總額是方向與額度，不等於已花完。",
      "再拆年度中央政府總預算、科技預算與運動部/國科會科目。註：年度預算才比較接近每年可執行的錢。",
      "最後比對地方核定、採購決標、驗收紀錄與成果報告。註：驗收或成果報告才代表案件比較接近落地。",
    ],
    sourceRefs: ["ey", "gstp", "dgbas", "data"] satisfies SourceKey[],
  },
  {
    label: "科研線索",
    value: "2.4 億元級",
    note: "精準運動科學歷史科研專案，重點在國家隊與競技表現。",
    detailTitle: "科研線索怎麼追",
    detail:
      "科研預算通常先支持研究團隊，不會立刻變成民眾看到的場館系統。它可能先變成 AI 模型、感測器、分析工具，之後才進入國家隊訓練或地方場域。",
    flow: ["研究計畫", "學研團隊", "模型/設備", "國訓/場域"],
    flowRoles: ["國科會/GRB", "大學與研究中心", "AI、感測與分析工具", "國訓中心、協會或地方場館"],
    flowIcons: ["search", "school", "cpu", "dumbbell"],
    checks: [
      "用 GRB 查計畫名稱、主持人、補助機關、執行期間與成果摘要。註：GRB 是政府研究計畫查詢系統。",
      "比對國科會新聞、補助公告與學校研究成果，確認是不是同一條計畫線。",
      "確認成果是否進入國訓中心、單項協會、地方場域或商品化應用。註：有研究成果不代表已經普及使用。",
    ],
    sourceRefs: ["nstc", "grb", "gstp", "sports"] satisfies SourceKey[],
  },
  {
    label: "地方案例",
    value: "14 縣市 / 30 案",
    note: "地方場域實證需分別查核核定、決標、驗收與維運。",
    detailTitle: "地方案例怎麼對帳",
    detail:
      "地方場域通常不是中央全額付款，而是中央補助、地方配合款和委外廠商一起完成。看到「14 縣市 / 30 案」時，要繼續追每一案是否已決標、驗收、維運和被民眾使用。",
    flow: ["中央核定", "地方配合款", "採購/委辦", "維運使用"],
    flowRoles: ["運動部/全民運動署", "縣市政府與議會", "得標廠商或受託單位", "場館營運者與民眾"],
    flowIcons: ["landmark", "building-2", "wrench", "users"],
    checks: [
      "先查地方府會預算書、議會質詢與中央補助核定，分開看中央款與地方款。註：配合款是地方自己也要出的錢。",
      "再查政府採購決標公告、契約廠商與驗收資訊，確認金額是否已形成契約。註：決標代表找到承作廠商。",
      "最後看系統上線、維運年度、使用人次與開放資料，避免只停在示範案數。",
    ],
    sourceRefs: ["sports", "pcc", "dgbas", "data"] satisfies SourceKey[],
  },
  {
    label: "協會角色",
    value: "5 項運動",
    note: "目前可辨識棒球、羽球、桌球、舉重、自由車等應用端線索。",
    detailTitle: "協會角色怎麼判斷",
    detail:
      "協會常出現在運動科技新聞裡，但不一定就是拿錢的單位。它可能只是提供選手、賽事、場地或專業意見。要判斷是否真的承接預算，要看補助名單、委辦契約、採購得標與成果報告。",
    flow: ["補助名單", "委辦契約", "合作露出", "實際承接"],
    flowRoles: ["運動部/補助公告", "採購或委辦契約", "協會、教練與選手", "受補助者或得標單位"],
    flowIcons: ["file-text", "handshake", "megaphone", "badge-check"],
    checks: [
      "查協會是否列為受補助者、委辦承攬者或採購得標單位。註：出現在新聞裡，不等於直接拿預算。",
      "區分合作露出、提供選手資料、提供賽事場域與實際經費承接。註：應用端是使用或協助測試的一方。",
      "比對成果報告、賽事資料與場域紀錄，確認科技導入後誰負責維運。",
    ],
    sourceRefs: ["sports", "pcc", "grb", "data"] satisfies SourceKey[],
  },
];

export const flows = [
  {
    id: "taiwan-sporttech",
    year: "2022-2026",
    title: "台灣運動 x 科技行動計畫",
    amount: "46 億元",
    source: "行政院跨部會科技預算",
    actors: ["運動部/前體育署", "國科會", "經濟部", "地方政府", "學研單位"],
    associations: ["棒球", "羽球", "桌球", "自由車", "游泳", "田徑"],
    locations: ["全國/跨縣市", "待逐案整理"],
    stage: "executing" as Stage,
    layer: "central" as Layer,
    publicness: "政策總額明確，逐年逐案流向仍需對帳。",
    note: "政策總額，分散於跨部會與跨年度項目，不宜直接視為運動部單一預算。",
    sourceRefs: ["ey", "nstc", "gstp", "dgbas", "data"] satisfies SourceKey[],
    publicInfo: {
      news: ["新聞與政策報導多以 2022-2026、46 億元跨部會投入為主，較少逐案列明年度支出。"],
      announcements: ["中央層級以行政院、科技會報、國科會與運動部政策說明為主要線索。"],
      openData: ["尚未見單一公開資料集可逐年對帳 46 億元流向；需拆到部會、年度與地方分案。"],
    } satisfies PublicInfo,
  },
  {
    id: "precision-sport-science",
    year: "2017-2024",
    title: "精準運動科學研究專案",
    amount: "2.4 億元級",
    source: "科技部/國科會科研預算",
    actors: ["大學研究團隊", "國家隊支援系統", "國家運動科學中心"],
    associations: ["羽球", "桌球", "棒球", "舉重", "自由車"],
    locations: ["全國/跨縣市"],
    stage: "verified" as Stage,
    layer: "research" as Layer,
    publicness: "歷史專案與成果可辨識，但分年支出仍需細表。",
    note: "重點在 AI 訓練、動作分析、疲勞監控、傷害預防與競技表現。",
    sourceRefs: ["nstc", "grb", "gstp", "sports"] satisfies SourceKey[],
    publicInfo: {
      news: ["公開討論包含精準運動科學研究、國科會補助與國家隊科技支援成果。"],
      announcements: ["中央線索在科技部/國科會研究計畫、學校研究公告與國家運動科學中心成果。"],
      openData: ["可查研究計畫名稱、主持人、補助金額與成果摘要，但完整運動別分年支出仍需逐案整理。"],
    } satisfies PublicInfo,
  },
  {
    id: "field-proof",
    year: "2022-2025",
    title: "地方運動科技場域實證",
    amount: "分案補助",
    source: "運動部公務預算 + 地方配合款",
    actors: ["14 縣市", "場館營運者", "科技廠商", "地方體育局"],
    associations: ["游泳", "田徑", "棒球", "全民運動"],
    locations: ["台北市", "新北市", "桃園市", "嘉義市", "高雄市", "待逐案整理"],
    stage: "executing" as Stage,
    layer: "local" as Layer,
    publicness: "案件數可辨識，逐案決標、驗收、維運需另查。",
    note: "公開資料顯示累計約 30 案；各案核定、決標、驗收、維運狀態不一致。",
    sourceRefs: ["sports", "pcc", "dgbas", "data"] satisfies SourceKey[],
    publicInfo: {
      news: ["地方案例常以智慧走跑、科技防溺、智慧場館或運動科技體驗活動形式出現在地方新聞。"],
      announcements: ["地方政府體育局、教育局公告、議會預算與政府採購決標是主要追蹤路徑。"],
      openData: ["已知有縣市與案件數線索，但每案核定、決標、驗收、維運、使用人次尚未形成統一 open data。"],
    } satisfies PublicInfo,
  },
  {
    id: "sports-fund",
    year: "年度型",
    title: "運動發展基金創新研發與數位轉型",
    amount: "約 3,000 萬元年度科目案例",
    source: "運動發展基金",
    actors: ["運動產業", "新創團隊", "法人", "地方政府"],
    associations: ["依合作案而定"],
    locations: ["全國/跨縣市", "待逐案整理"],
    stage: "executing" as Stage,
    layer: "industry" as Layer,
    publicness: "年度科目可辨識，受補助名單與成果需逐案整理。",
    note: "偏向產品、服務、數位轉型、產學合作和商業模式驗證。",
    sourceRefs: ["sports", "dgbas", "pcc", "data"] satisfies SourceKey[],
    publicInfo: {
      news: ["較常出現在運動產業創新、數位轉型、新創補助與產學合作報導。"],
      announcements: ["線索集中在運動發展基金年度預算、補助要點、受補助名單或成果發表。"],
      openData: ["年度科目可辨識，但受補助團隊、補助額、成果與後續營收需逐案公開對帳。"],
    } satisfies PublicInfo,
  },
  {
    id: "application-budget",
    year: "年度型",
    title: "運動科技應用發展",
    amount: "約 3,567 萬元年度科目案例",
    source: "體育署/運動部年度公務預算",
    actors: ["地方政府", "學校", "委辦團隊", "場域夥伴"],
    associations: ["依場域而定"],
    locations: ["全國/跨縣市", "待逐案整理"],
    stage: "verified" as Stage,
    layer: "central" as Layer,
    publicness: "科目案例清楚，但非所有運動科技經費總額。",
    note: "用於地方科技場域、跨域人才與應用推廣；只是特定年度可辨識科目。",
    sourceRefs: ["sports", "dgbas", "pcc", "data"] satisfies SourceKey[],
    publicInfo: {
      news: ["多以運動科技應用、地方場域、人才培育、體驗競賽等活動型新聞出現。"],
      announcements: ["主要查運動部/前體育署年度預算、單位預算與相關委辦、補助公告。"],
      openData: ["科目案例可辨識，但不是完整運動科技總額；需和資訊服務費、場館設備、委辦費分開查。"],
    } satisfies PublicInfo,
  },
  {
    id: "baseball-made",
    year: "2025-2026",
    title: "國球國造：棒球運動科技場域淬鍊",
    amount: "待核定公開",
    source: "爭取 115 年度國科會科技預算",
    actors: ["國科會", "運動部", "天母棒球場經驗模型", "縣市場館"],
    associations: ["棒球"],
    locations: ["台北市", "待擴散縣市"],
    stage: "proposal" as Stage,
    layer: "research" as Layer,
    publicness: "目前宜列提案/爭取，不宜寫成已全面執行。",
    note: "目前較適合列為提案/預算爭取，不宜描述為已全面執行。",
    sourceRefs: ["nstc", "gstp", "sports", "pcc"] satisfies SourceKey[],
    publicInfo: {
      news: ["目前公開資訊多指向天母棒球場經驗、棒球科技場域與國產技術驗證構想。"],
      announcements: ["應追蹤 115 年度國科會科技預算、運動部提案與後續採購或補助公告。"],
      openData: ["尚屬提案/爭取與模型規劃階段；未見完整核定金額、得標廠商與擴散縣市清單。"],
    } satisfies PublicInfo,
  },
  {
    id: "aspn",
    year: "2025-2026",
    title: "ASPN 國際運動科技創新加速器",
    amount: "委辦與補助細目待公開",
    source: "運動部產業與科技相關預算",
    actors: ["陽明交通大學 IAPS", "新創團隊", "國際市場夥伴"],
    associations: ["依場域測試而定"],
    locations: ["全國/跨縣市", "待逐案整理"],
    stage: "executing" as Stage,
    layer: "industry" as Layer,
    publicness: "活動與成果可見，完整成本拆分仍待公開。",
    note: "可見活動與成果，但完整委辦金額、新創補助與行政成本仍需對帳。",
    sourceRefs: ["sports", "pcc", "dgbas", "data"] satisfies SourceKey[],
    publicInfo: {
      news: ["公開資訊以 ASPN 國際運動科技創新加速器徵案、入選團隊、國際展會與 Demo Day 為主。"],
      announcements: ["可追陽明交通大學 IAPS、運動部產業科技計畫、委辦或徵案公告。"],
      openData: ["活動成果可見，但委辦金額、新創補助、展會費用與場域驗證成本仍需拆帳。"],
    } satisfies PublicInfo,
  },
  {
    id: "association-use",
    year: "持續",
    title: "協會端科技導入與國家隊應用",
    amount: "多非直接預算主體",
    source: "大學/研究中心/國科會/運動部計畫轉介",
    actors: ["單項協會", "教練", "選手", "研究團隊"],
    associations: ["棒球", "羽球", "桌球", "舉重", "自由車"],
    locations: ["全國/跨縣市", "待逐案整理"],
    stage: "unknown" as Stage,
    layer: "association" as Layer,
    publicness: "需逐案釐清協會是受補助者、合作方或應用場域。",
    note: "協會多為合作場域、選手資料與應用端，不一定是科技預算直接受補助者。",
    sourceRefs: ["sports", "nstc", "grb", "data"] satisfies SourceKey[],
    publicInfo: {
      news: ["協會端多出現在特定運動科技導入、國家隊訓練、選手數據分析或賽事情蒐報導。"],
      announcements: ["需比對單項協會、國訓中心、國家運動科學中心與研究團隊合作公告。"],
      openData: ["目前應標為應用端線索；需逐案確認協會是受補助者、合作方、資料提供者或場域使用者。"],
    } satisfies PublicInfo,
  },
];

export const sportBudgetRows = [
  {
    sport: "棒球",
    theme: "棒球科技場域、軌跡分析與國家隊支援",
    budgetClues: ["台灣運動 x 科技行動計畫", "精準運動科學研究專案", "國球國造：棒球運動科技場域淬鍊"],
    flowRefs: ["taiwan-sporttech", "precision-sport-science", "baseball-made"],
    amount: "46 億元政策總盤之一；另有 2.4 億元級科研線索與待核定新案",
    status: "提案與執行並存",
    associationRole: "棒球協會或場館多為應用端、賽事與選手資料合作端；是否直接受補助仍需逐案確認。",
    nextCheck: "查 115 年度國科會科技預算、天母棒球場模型、採購決標與後續縣市導入名單。",
    sourceRefs: ["nstc", "gstp", "sports", "pcc"] satisfies SourceKey[],
  },
  {
    sport: "羽球",
    theme: "AI 訓練、動作分析與國家隊競技支援",
    budgetClues: ["精準運動科學研究專案", "協會端科技導入與國家隊應用"],
    flowRefs: ["precision-sport-science", "association-use"],
    amount: "2.4 億元級科研專案中的可辨識運動別線索",
    status: "已有成果",
    associationRole: "協會較可能提供選手、教練與訓練場域，不宜直接推定為科技預算受補助者。",
    nextCheck: "用 GRB 查研究計畫、主持人與成果摘要，再比對國訓中心或協會合作公告。",
    sourceRefs: ["nstc", "grb", "sports"] satisfies SourceKey[],
  },
  {
    sport: "桌球",
    theme: "擊球分析、戰術資料與競技表現支援",
    budgetClues: ["精準運動科學研究專案", "協會端科技導入與國家隊應用"],
    flowRefs: ["precision-sport-science", "association-use"],
    amount: "2.4 億元級科研專案中的可辨識運動別線索",
    status: "已有成果",
    associationRole: "協會角色多在國家隊訓練、選手資料或測試場域，直接預算關係需回查補助或委辦資料。",
    nextCheck: "查國科會、GRB 與國家運動科學中心成果，再比對協會是否列入受補助或合作單位。",
    sourceRefs: ["nstc", "grb", "sports"] satisfies SourceKey[],
  },
  {
    sport: "舉重",
    theme: "力量監測、疲勞分析與傷害預防",
    budgetClues: ["精準運動科學研究專案", "協會端科技導入與國家隊應用"],
    flowRefs: ["precision-sport-science", "association-use"],
    amount: "2.4 億元級科研專案中的可辨識運動別線索",
    status: "已有成果",
    associationRole: "協會可能協助訓練資料、教練與選手端導入；金流仍以學研或國訓支援線索優先查核。",
    nextCheck: "追研究成果是否進入國訓中心、代表隊訓練或器材採購，避免只看新聞露出。",
    sourceRefs: ["grb", "sports", "pcc"] satisfies SourceKey[],
  },
  {
    sport: "自由車",
    theme: "功率、生理監測與訓練數據分析",
    budgetClues: ["精準運動科學研究專案", "台灣運動 x 科技行動計畫"],
    flowRefs: ["precision-sport-science", "taiwan-sporttech", "association-use"],
    amount: "2.4 億元級科研線索；也可能落在 46 億元政策總盤的應用端",
    status: "已有成果 / 執行中",
    associationRole: "協會或隊伍多為測試、訓練與應用端；需查是否有設備採購或專案補助。",
    nextCheck: "比對穿戴裝置、訓練設備、研究計畫成果與採購公告是否指向同一筆預算。",
    sourceRefs: ["nstc", "grb", "pcc", "data"] satisfies SourceKey[],
  },
  {
    sport: "游泳",
    theme: "科技防溺、泳池場域管理與動作資料",
    budgetClues: ["地方運動科技場域實證", "運動科技應用發展"],
    flowRefs: ["field-proof", "application-budget"],
    amount: "多為分案補助或年度科目案例，需查中央補助與地方配合款",
    status: "執行中",
    associationRole: "游泳相關協會不一定是預算主體，常見角色可能是場域需求、教練或安全規範意見提供。",
    nextCheck: "查新北、高雄等科技防溺或泳池案的地方預算、決標廠商、驗收與維運費。",
    sourceRefs: ["sports", "pcc", "dgbas", "data"] satisfies SourceKey[],
  },
  {
    sport: "田徑",
    theme: "智慧跑道、走跑場域與全民運動數據",
    budgetClues: ["地方運動科技場域實證", "運動科技應用發展"],
    flowRefs: ["field-proof", "application-budget"],
    amount: "多為地方分案補助、年度科目與維運費，不宜直接併入單項協會預算",
    status: "執行中",
    associationRole: "田徑相關組織多可能出現在活動、競賽或場域使用端；直接受補助需看名單。",
    nextCheck: "查嘉義智慧跑道、桃園/高雄智慧走跑等地方公告、APP 維運與使用人次資料。",
    sourceRefs: ["sports", "pcc", "data"] satisfies SourceKey[],
  },
  {
    sport: "全民運動",
    theme: "智慧場館、走跑活動、運動資料平台與使用者服務",
    budgetClues: ["台灣運動 x 科技行動計畫", "地方運動科技場域實證", "運動發展基金創新研發與數位轉型"],
    flowRefs: ["taiwan-sporttech", "field-proof", "sports-fund", "application-budget"],
    amount: "46 億元政策總盤、地方分案補助與約 3,000 萬元年度基金科目案例皆可能相關",
    status: "執行中 / 待公開對帳",
    associationRole: "多數情境不是單項協會主導，而是地方政府、場館營運者、新創、法人或學研單位執行。",
    nextCheck: "拆成政策總額、年度科目、地方配合款、委辦案與維運費，再查使用人次與 open data。",
    sourceRefs: ["ey", "sports", "dgbas", "data"] satisfies SourceKey[],
  },
];

export const stageOrder: Stage[] = [
  "proposal",
  "approved",
  "executing",
  "verified",
  "unknown",
];

export const locationNames: Record<string, string> = Object.fromEntries(
  Array.from(new Set(flows.flatMap((flow) => flow.locations))).map((location) => [
    location,
    location,
  ]),
);
